In [1]:
import numpy as np
import pandas as pd

<h1>DataFrame</h1>

In [2]:
labels = [1,2,3]
my_list = [10,20,30]
arr = pd.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}

In [3]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [4]:
pd.Series(my_list, index = labels)

1    10
2    20
3    30
dtype: int64

In [5]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: Int64

<h1>DataFrame</h1>

In [7]:
data = {
    'Name' :['John', 'Anna', 'Peter', 'Linda'],
    'Age' :[28,34,29,42],
    'City':['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [8]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [9]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ['Name', 'Age', 'City', 'Salary']
df2 = pd.DataFrame(data_list, columns = columns)

In [10]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

<h1>Selection and indexing of columns</h1>

In [12]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [13]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

<h1>Creating a new column</h1>

In [14]:
df2['destination'] = ['Doctor', 'Engineer', 'Doctor', 'Engineer']
df2

    Name  Age      City  Salary destination
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

In [15]:
df2.drop('destination', axis =1)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [16]:
df2.loc[0]

Name               John
Age                  28
City           New York
Salary            65000
destination      Doctor
Name: 0, dtype: object

In [17]:
df2.loc[[0,1]]

   Name  Age      City  Salary destination
0  John   28  New York   65000      Doctor
1  Anna   34     Paris   70000    Engineer

In [18]:
df2.iloc[3]

Name              Linda
Age                  42
City             London
Salary            85000
destination    Engineer
Name: 3, dtype: object

<h1>Selecting subset of rows and columns</h1>

In [19]:
df.loc[[2,3]][['City', 'Salary']]

     City  Salary
2  Berlin   62000
3  London   85000

<h1>Conditional Selection</h1>

In [20]:
#i only want to see whose age is above 30

In [21]:
df2[df2['Age']> 30]

    Name  Age    City  Salary destination
1   Anna   34   Paris   70000    Engineer
3  Linda   42  London   85000    Engineer

In [22]:
df2[(df2['Age']>30) & (df2['City'] == 'Paris')]

   Name  Age   City  Salary destination
1  Anna   34  Paris   70000    Engineer

<h1>Missing Data<h1>

In [23]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [24]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [25]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [26]:
#this works with the columns
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [27]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [28]:
df.dropna(thresh = 3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [29]:
df.dropna(thresh = 1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [30]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [31]:
values = {'A' : 0, 'B' : 200, 'C': 300, 'D': 400}
df.fillna(value = values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [32]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

<h1>Merging joining and concatination</h1>

In [33]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [34]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [35]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [36]:
pd.merge(employees, salaries, on='employee_id', how ="inner")

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [37]:
pd.merge(employees, salaries, on = 'employee_id', how = 'outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [38]:
pd.merge(employees, salaries, on = 'employee_id', how = 'left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [39]:
pd.merge(employees, salaries, on = 'employee_id', how = 'right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

<h1>concatination of two dataframes</h1>

In [40]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [41]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [42]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [43]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [44]:
pd.concat([df1, df2], axis = 1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

**joining two dataframes**

In [45]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [46]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [47]:
df2

   score
2     85
3     90
4     75

In [48]:
df1.join(df2)

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [49]:
df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

<h1>Grouped by Aggregation</h1>

In [50]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [51]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [52]:
#Group by  category and calculate the sum of sales
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [53]:
#Group by multiple columns
#Group by category and Store
cat = df.groupby(['Category', 'Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [54]:
df['Sales'].mean()

np.float64(187.5)

In [57]:
df['Sales'].agg(['mean', 'std', 'max', 'min'])
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

<h1>Pivot tables</h1>

In [58]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    509     14   John  January      Q1
1  2023-01-02       B   West    880     70   Mary  January      Q1
2  2023-01-03       C  North    473     84    Bob  January      Q1
3  2023-01-04       D  South    991     70  Alice  January      Q1
4  2023-01-05       A   East    425     45   John  January      Q1
5  2023-01-06       B   West    729     95   Mary  January      Q1
6  2023-01-07       C  North    702     66    Bob  January      Q1
7  2023-01-08       D  South    437     93  Alice  January      Q1
8  2023-01-09       A   East    636     30   John  January      Q1
9  2023-01-10       B   West    479     23   Mary  January      Q1
10 2023-01-11       C  North    337     26    Bob  January      Q1
11 2023-01-12       D  South    200     71  Alice  January      Q1
12 2023-01-13       A   East    558     57   John  January      Q1
13 2023-01-14       B   West    394     77   Mary  January      Q1
14 2023-01-15       C  North    983     94    Bob  January      Q1
15 2023-01-16       D  South    469     61  Alice  January      Q1
16 2023-01-17       A   East    172     31   John  January      Q1
17 2023-01-18       B   West    260     85   Mary  January      Q1
18 2023-01-19       C  North    237     67    Bob  January      Q1
19 2023-01-20       D  South    906     43  Alice  January      Q1

In [62]:
pd.pivot_table(df, values = 'Sales', index = 'Region', columns = 'Product', aggfunc = 'median')

Product      A      B      C      D
Region
East     509.0    NaN    NaN    NaN
North      NaN    NaN  473.0    NaN
South      NaN    NaN    NaN  469.0
West       NaN  479.0    NaN    NaN

In [64]:
pd.pivot_table(df, values =['Sales', 'Units'], index = 'Region', columns = 'Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     460.0    NaN    NaN    NaN  35.4   NaN   NaN   NaN
North      NaN    NaN  546.4    NaN   NaN   NaN  67.4   NaN
South      NaN    NaN    NaN  600.6   NaN   NaN   NaN  67.6
West       NaN  548.4    NaN    NaN   NaN  70.0   NaN   NaN

In [66]:
pd.crosstab(df['Region'], df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

<h1>Operations</h1>

In [67]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [68]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [69]:
df1.shape

(5, 3)

In [70]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [71]:
df.info

<bound method DataFrame.info of          Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    509     14   John  January      Q1
1  2023-01-02       B   West    880     70   Mary  January      Q1
2  2023-01-03       C  North    473     84    Bob  January      Q1
3  2023-01-04       D  South    991     70  Alice  January      Q1
4  2023-01-05       A   East    425     45   John  January      Q1
5  2023-01-06       B   West    729     95   Mary  January      Q1
6  2023-01-07       C  North    702     66    Bob  January      Q1
7  2023-01-08       D  South    437     93  Alice  January      Q1
8  2023-01-09       A   East    636     30   John  January      Q1
9  2023-01-10       B   West    479     23   Mary  January      Q1
10 2023-01-11       C  North    337     26    Bob  January      Q1
11 2023-01-12       D  South    200     71  Alice  January      Q1
12 2023-01-13       A   East    558     57   John  January      Q1
13 2023-01-14       B   West    394     77   Mary  January      Q1
14 2023-01-15       C  North    983     94    Bob  January      Q1
15 2023-01-16       D  South    469     61  Alice  January      Q1
16 2023-01-17       A   East    172     31   John  January      Q1
17 2023-01-18       B   West    260     85   Mary  January      Q1
18 2023-01-19       C  North    237     67    Bob  January      Q1
19 2023-01-20       D  South    906     43  Alice  January      Q1>

In [72]:
df.describe()

                      Date       Sales      Units
count                   20   20.000000  20.000000
mean   2023-01-10 12:00:00  538.850000  60.100000
min    2023-01-01 00:00:00  172.000000  14.000000
25%    2023-01-05 18:00:00  379.750000  40.000000
50%    2023-01-10 12:00:00  476.000000  66.500000
75%    2023-01-15 06:00:00  708.750000  78.750000
max    2023-01-20 00:00:00  991.000000  95.000000
std                    NaN  255.722768  25.414252

In [73]:
df1['A'] +10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [74]:
def square(x):
    return x**2

In [78]:
df1['D'] = df1['B'].apply(square)
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500